package observer

import (
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

func TestGenerateFullObservation(t *testing.T) {
	exitCode := 0
	obs := &Observation{
		Command:  "node server.js",
		ExitCode: 0,
		Stdout:   "Server ready on port 3000\nListening for connections",
		Stderr:   "",
		Ports: []PortBinding{
			{Port: 3000, Protocol: "tcp", Host: "0.0.0.0"},
		},
		NewFiles: []FileSnapshot{
			{Path: "dist/bundle.js", Size: 1024, Hash: "abc123"},
		},
		HTTPProbes: []HTTPProbeResult{
			{URL: "http://localhost:3000/health", StatusCode: 200, Reachable: true},
		},
	}

	out, err := Generate(obs)
	if err != nil {
		t.Fatalf("Generate() error: %v", err)
	}

	raw := string(out)

	// Verify header comment
	if !strings.HasPrefix(raw, "# Generated by:") {
		t.Error("output missing header comment")
	}
	if !strings.Contains(raw, `smokesig observe "node server.js"`) {
		t.Error("header missing command")
	}

	// Verify roundtrip through yaml.Unmarshal
	var cfg generatedConfig
	if err := unmarshalYAML(out, &cfg); err != nil {
		t.Fatalf("output is not valid YAML: %v", err)
	}

	if cfg.Version != 1 {
		t.Errorf("Version = %d, want 1", cfg.Version)
	}
	if cfg.Project != "node" {
		t.Errorf("Project = %q, want %q", cfg.Project, "node")
	}

	// Expect 5 tests: exit, stdout, port, file, http
	if len(cfg.Tests) != 5 {
		t.Fatalf("len(Tests) = %d, want 5; got: %+v", len(cfg.Tests), cfg.Tests)
	}

	// Test 1: command-exit
	assertTest(t, cfg.Tests[0], "command-exit", &exitCode, "", nil, "", nil)

	// Test 2: stdout-check
	assertTest(t, cfg.Tests[1], "stdout-check", nil, "Server ready on port 3000", nil, "", nil)

	// Test 3: port-3000
	assertTest(t, cfg.Tests[2], "port-3000", nil, "", &generatedPortCheck{Port: 3000, Protocol: "tcp"}, "", nil)

	// Test 4: file-dist-bundle-js
	assertTest(t, cfg.Tests[3], "file-dist-bundle-js", nil, "", nil, "dist/bundle.js", nil)

	// Test 5: http-health
	assertTest(t, cfg.Tests[4], "http-health", nil, "", nil, "", &generatedHTTPCheck{URL: "http://localhost:3000/health", StatusCode: intPtr(200)})
}

func TestGenerateEmptyObservation(t *testing.T) {
	obs := &Observation{
		Command:  "echo hello",
		ExitCode: 0,
	}

	out, err := Generate(obs)
	if err != nil {
		t.Fatalf("Generate() error: %v", err)
	}

	var cfg generatedConfig
	if err := unmarshalYAML(out, &cfg); err != nil {
		t.Fatalf("output is not valid YAML: %v", err)
	}

	if len(cfg.Tests) != 1 {
		t.Fatalf("len(Tests) = %d, want 1", len(cfg.Tests))
	}
	if cfg.Tests[0].Name != "command-exit" {
		t.Errorf("Test name = %q, want %q", cfg.Tests[0].Name, "command-exit")
	}
}

func TestGenerateNoStdoutKeywords(t *testing.T) {
	obs := &Observation{
		Command:  "ls /tmp",
		ExitCode: 0,
		Stdout:   "file1.txt\nfile2.txt\nfile3.txt",
	}

	out, err := Generate(obs)
	if err != nil {
		t.Fatalf("Generate() error: %v", err)
	}

	var cfg generatedConfig
	if err := unmarshalYAML(out, &cfg); err != nil {
		t.Fatalf("output is not valid YAML: %v", err)
	}

	// ExtractKeyPhrases with no keyword matches returns first and last line
	// So there should be a stdout-check test with first line
	stdoutTests := 0
	for _, tt := range cfg.Tests {
		if tt.Expect.StdoutContains != "" {
			stdoutTests++
		}
	}
	if stdoutTests == 0 {
		t.Error("expected at least one stdout test even without keyword matches")
	}
}

func TestGenerateYAMLRoundtrip(t *testing.T) {
	obs := &Observation{
		Command:  "make build",
		ExitCode: 1,
		Stdout:   "Build failed with error in main.go",
		Ports: []PortBinding{
			{Port: 8080, Protocol: "tcp"},
			{Port: 9090, Protocol: "udp"},
		},
		NewFiles: []FileSnapshot{
			{Path: "output.bin", Size: 2048, Hash: "def456"},
		},
		HTTPProbes: []HTTPProbeResult{
			{URL: "http://example.com/api", StatusCode: 404, Reachable: true},
			{URL: "http://example.com/down", StatusCode: 0, Reachable: false},
		},
	}

	out, err := Generate(obs)
	if err != nil {
		t.Fatalf("Generate() error: %v", err)
	}

	var cfg generatedConfig
	if err := unmarshalYAML(out, &cfg); err != nil {
		t.Fatalf("unmarshal error: %v", err)
	}

	if cfg.Project != "make" {
		t.Errorf("Project = %q, want %q", cfg.Project, "make")
	}

	// Exit code 1
	if cfg.Tests[0].Expect.ExitCode == nil || *cfg.Tests[0].Expect.ExitCode != 1 {
		t.Error("first test exit_code should be 1")
	}

	// Unreachable HTTP should not generate a test
	httpCount := 0
	for _, tt := range cfg.Tests {
		if tt.Expect.HTTP != nil {
			httpCount++
		}
	}
	if httpCount != 1 {
		t.Errorf("http tests = %d, want 1 (unreachable should be excluded)", httpCount)
	}

	// Re-marshal and unmarshal again to verify full roundtrip
	out2, err := yamlMarshalConfig(&cfg)
	if err != nil {
		t.Fatalf("re-marshal error: %v", err)
	}
	var cfg2 generatedConfig
	if err := unmarshalYAML(out2, &cfg2); err != nil {
		t.Fatalf("re-unmarshal error: %v", err)
	}
	if len(cfg2.Tests) != len(cfg.Tests) {
		t.Errorf("roundtrip changed test count: %d -> %d", len(cfg.Tests), len(cfg2.Tests))
	}
}

func TestDeriveProject(t *testing.T) {
	tests := []struct {
		cmd  string
		want string
	}{
		{"node server.js", "node"},
		{"go run ./...", "go"},
		{"python app.py", "python"},
		{"", "unknown"},
		{"  ", "unknown"},
	}
	for _, tt := range tests {
		got := deriveProject(tt.cmd)
		if got != tt.want {
			t.Errorf("deriveProject(%q) = %q, want %q", tt.cmd, got, tt.want)
		}
	}
}

func TestFileTestName(t *testing.T) {
	tests := []struct {
		path string
		want string
	}{
		{"dist/bundle.js", "file-dist-bundle-js"},
		{"output.txt", "file-output-txt"},
		{"Makefile", "file-makefile"},
	}
	for _, tt := range tests {
		got := fileTestName(tt.path)
		if got != tt.want {
			t.Errorf("fileTestName(%q) = %q, want %q", tt.path, got, tt.want)
		}
	}
}

func TestHTTPTestName(t *testing.T) {
	tests := []struct {
		url  string
		want string
	}{
		{"http://localhost:3000/health", "http-health"},
		{"https://example.com/api/v1/status", "http-api-v1-status"},
		{"http://myservice.local", "http-myservice-local"},
	}
	for _, tt := range tests {
		got := httpTestName(tt.url)
		if got != tt.want {
			t.Errorf("httpTestName(%q) = %q, want %q", tt.url, got, tt.want)
		}
	}
}

// helpers

func unmarshalYAML(data []byte, cfg *generatedConfig) error {
	// Strip header comment before unmarshaling
	lines := strings.Split(string(data), "\n")
	var yamlLines []string
	for _, line := range lines {
		if !strings.HasPrefix(line, "#") {
			yamlLines = append(yamlLines, line)
		}
	}
	return yaml.Unmarshal([]byte(strings.Join(yamlLines, "\n")), cfg)
}

func yamlMarshalConfig(cfg *generatedConfig) ([]byte, error) {
	return yaml.Marshal(cfg)
}

func assertTest(t *testing.T, gt generatedTest, name string, exitCode *int, stdoutContains string, port *generatedPortCheck, fileExists string, http *generatedHTTPCheck) {
	t.Helper()
	if gt.Name != name {
		t.Errorf("test name = %q, want %q", gt.Name, name)
	}
	if exitCode != nil {
		if gt.Expect.ExitCode == nil || *gt.Expect.ExitCode != *exitCode {
			t.Errorf("exit_code mismatch: got %v, want %d", gt.Expect.ExitCode, *exitCode)
		}
	}
	if stdoutContains != "" && gt.Expect.StdoutContains != stdoutContains {
		t.Errorf("stdout_contains = %q, want %q", gt.Expect.StdoutContains, stdoutContains)
	}
	if port != nil {
		if gt.Expect.PortListening == nil {
			t.Error("port_listening is nil")
		} else {
			if gt.Expect.PortListening.Port != port.Port {
				t.Errorf("port = %d, want %d", gt.Expect.PortListening.Port, port.Port)
			}
			if gt.Expect.PortListening.Protocol != port.Protocol {
				t.Errorf("protocol = %q, want %q", gt.Expect.PortListening.Protocol, port.Protocol)
			}
		}
	}
	if fileExists != "" && gt.Expect.FileExists != fileExists {
		t.Errorf("file_exists = %q, want %q", gt.Expect.FileExists, fileExists)
	}
	if http != nil {
		if gt.Expect.HTTP == nil {
			t.Error("http is nil")
		} else {
			if gt.Expect.HTTP.URL != http.URL {
				t.Errorf("http URL = %q, want %q", gt.Expect.HTTP.URL, http.URL)
			}
			if http.StatusCode != nil {
				if gt.Expect.HTTP.StatusCode == nil || *gt.Expect.HTTP.StatusCode != *http.StatusCode {
					t.Errorf("http status_code mismatch")
				}
			}
		}
	}
}

func intPtr(v int) *int { return &v }
