package observer

import (
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

type generatedConfig struct {
	Version int             `yaml:"version"`
	Project string          `yaml:"project"`
	Tests   []generatedTest `yaml:"tests"`
}

type generatedTest struct {
	Name   string          `yaml:"name"`
	Run    string          `yaml:"run,omitempty"`
	Expect generatedExpect `yaml:"expect"`
}

type generatedExpect struct {
	ExitCode       *int                `yaml:"exit_code,omitempty"`
	StdoutContains string              `yaml:"stdout_contains,omitempty"`
	PortListening  *generatedPortCheck `yaml:"port_listening,omitempty"`
	FileExists     string              `yaml:"file_exists,omitempty"`
	HTTP           *generatedHTTPCheck `yaml:"http,omitempty"`
}

type generatedPortCheck struct {
	Port     int    `yaml:"port"`
	Protocol string `yaml:"protocol"`
}

type generatedHTTPCheck struct {
	URL        string `yaml:"url"`
	StatusCode *int   `yaml:"status_code,omitempty"`
}

func ptrInt(v int) *int { return &v }

// Generate converts an Observation into YAML bytes representing a .smokesig.yaml config.
func Generate(obs *Observation) ([]byte, error) {
	project := deriveProject(obs.Command)
	var tests []generatedTest

	// 1. Command exit code (always)
	exitCode := obs.ExitCode
	tests = append(tests, generatedTest{
		Name: "command-exit",
		Run:  obs.Command,
		Expect: generatedExpect{
			ExitCode: &exitCode,
		},
	})

	// 2. Stdout key phrases
	cleaned := Sanitize(obs.Stdout)
	phrases := ExtractKeyPhrases(cleaned)
	if len(phrases) > 0 {
		tests = append(tests, generatedTest{
			Name: "stdout-check",
			Expect: generatedExpect{
				StdoutContains: phrases[0],
			},
		})
	}

	// 3. Port listening assertions
	for _, p := range obs.Ports {
		tests = append(tests, generatedTest{
			Name: fmt.Sprintf("port-%d", p.Port),
			Expect: generatedExpect{
				PortListening: &generatedPortCheck{
					Port:     p.Port,
					Protocol: defaultStr(p.Protocol, "tcp"),
				},
			},
		})
	}

	// 4. File exists assertions
	for _, f := range obs.NewFiles {
		name := fileTestName(f.Path)
		tests = append(tests, generatedTest{
			Name: name,
			Expect: generatedExpect{
				FileExists: f.Path,
			},
		})
	}

	// 5. HTTP assertions
	for _, h := range obs.HTTPProbes {
		if h.Reachable {
			expect := generatedHTTPCheck{
				URL:        h.URL,
				StatusCode: nil,
			}
			if h.StatusCode > 0 {
				expect.StatusCode = ptrInt(h.StatusCode)
			}
			tests = append(tests, generatedTest{
				Name: httpTestName(h.URL),
				Expect: generatedExpect{
					HTTP: &expect,
				},
			})
		}
	}

	cfg := generatedConfig{
		Version: 1,
		Project: project,
		Tests:   tests,
	}

	out, err := yaml.Marshal(&cfg)
	if err != nil {
		return nil, fmt.Errorf("marshal config: %w", err)
	}

	header := fmt.Sprintf("# Generated by: smokesig observe %q\n", obs.Command)
	return append([]byte(header), out...), nil
}

func deriveProject(cmd string) string {
	parts := strings.Fields(cmd)
	if len(parts) == 0 {
		return "unknown"
	}
	return parts[0]
}

func defaultStr(val, def string) string {
	if val == "" {
		return def
	}
	return val
}

func fileTestName(path string) string {
	// Use full path (with slashes replaced) for more descriptive names
	name := strings.ReplaceAll(path, "/", "-")
	name = strings.ReplaceAll(name, ".", "-")
	name = strings.ToLower(name)
	name = strings.Trim(name, "-")
	if name == "" {
		name = "file-exists"
	}
	return "file-" + name
}

func httpTestName(url string) string {
	// Extract path or host for a readable test name
	u := url
	u = strings.TrimPrefix(u, "http://")
	u = strings.TrimPrefix(u, "https://")
	parts := strings.SplitN(u, "/", 2)
	host := parts[0]
	path := ""
	if len(parts) > 1 {
		path = parts[1]
	}
	if path != "" {
		path = strings.ReplaceAll(path, "/", "-")
		path = strings.TrimRight(path, "-")
		return "http-" + sanitizeName(path)
	}
	return "http-" + sanitizeName(host)
}

func sanitizeName(s string) string {
	s = strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '-' {
			return r
		}
		if r >= 'A' && r <= 'Z' {
			return r + 32
		}
		return '-'
	}, s)
	s = strings.Trim(s, "-")
	// Deduplicate dashes
	var b strings.Builder
	prev := false
	for _, r := range s {
		if r == '-' {
			if prev {
				continue
			}
			prev = true
		} else {
			prev = false
		}
		b.WriteRune(r)
	}
	result := b.String()
	if result == "" {
		return "endpoint"
	}
	return result
}

